[package]
name = "fakhr"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
bitcoin = { version = "0.32.5", features = ["rand-std"] }
clap = { version = "4.5.35", features = ["derive"] }
